on:
  push: 
    branches: ["cicd-setup"]

  pull_request: {}

jobs:
  buil:
    name: test-ubuntu
    runs-on: ubuntu-latest

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3

#       - name: install mesa
#         run: |
#           sudo add-apt-repository ppa:kisak/kisak-mesa
#           sudo apt update
#           sudo apt upgrade

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
